<a href="https://colab.research.google.com/github/Mohammed-Elkhamlichi/SQL_Notebook_Practice/blob/main/Resources/DataBase_Overview_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PART 1: DATABASE OVERVIEW**

<a target="_blank" href="https://colab.research.google.com/github/Mohammed-Elkhamlichi/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# **`Import Libraries & Database`**

In [18]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql psycopg2-binary > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql+psycopg2://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

# **`Public Tables`**

In [4]:
%%sql
select table_name
from information_schema.tables
where table_schema = 'public'

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

# **`CurrencyExchange Table`**

In [8]:
%%sql
select *
from currencyexchange
limit 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

         date fromcurrency tocurrency  exchange
0  2015-01-01          AUD        AUD      1.00
1  2015-01-01          AUD        CAD      0.95
2  2015-01-01          AUD        EUR      0.67
3  2015-01-01          AUD        GBP      0.53
4  2015-01-01          AUD        USD      0.82
5  2015-01-01          CAD        AUD      1.05
6  2015-01-01          CAD        CAD      1.00
7  2015-01-01          CAD        EUR      0.71
8  2015-01-01          CAD        GBP      0.55
9  2015-01-01          CAD        USD      0.86

# **`Customer Table`**

In [9]:
%%sql
select *
from customer
limit 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17
1,23,8,1995-08-11,2045-01-26,Australia,female,Ms.,Rose,H,Dash,...,6055,AU,Australia,1990-05-10,30,Agricultural and food scientist,Rack N Sack,2005 Volvo XC90,-31.92,116.05
2,36,2,1992-03-12,2044-05-14,Australia,female,Ms.,Annabelle,J,Townsend,...,2304,AU,Australia,1964-07-16,56,Special education teacher,id Boutiques,1999 Lancia Lybra,-32.88,151.71
3,120,6,1983-07-23,2033-08-09,Australia,male,Mr.,Jamie,H,Hetherington,...,7256,AU,Australia,1946-12-11,74,Dental laboratory technician,Showbiz Pizza Place,2006 Dodge Durango,-39.77,144.02
4,180,7,1987-11-26,2026-10-14,Australia,male,Mr.,Gabriel,P,Bosanquet,...,3505,AU,Australia,1955-04-24,65,Administrative support specialist,Dubrow's Cafeteria,1995 Morgan Plus 4,-34.13,142.14
5,185,2,1990-08-01,2029-05-28,Australia,female,Mrs.,Gabrielle,B,Castella,...,2469,AU,Australia,1980-02-23,40,Management dietitian,d.e.m.o.,1997 Alpina B6,-29.01,152.84
6,189,7,2008-07-05,2017-11-01,Australia,female,Ms.,Hayley,C,Jull,...,3377,AU,Australia,1960-04-18,60,Sculptor,Asian Plan,2006 Alpina B5,-37.34,142.91
7,210,2,1980-09-28,2030-05-08,Australia,female,Mrs.,Natalie,L,Hilder,...,2632,AU,Australia,1950-11-23,70,Motel desk clerk,Enrich Garden Services,1995 Ford Fairlane,-36.84,149.05
8,225,7,1985-06-25,2017-09-25,Australia,male,Mr.,Hunter,J,Hutchins,...,3763,AU,Australia,1978-07-20,42,Teletype operator,Mr. Good Buys,2012 Lexus GX,-37.51,145.44
9,243,2,1982-02-07,2027-02-09,Australia,female,Ms.,Maya,J,Atherton,...,2446,AU,Australia,1954-05-15,66,Pilates instructor,Franklin Music,1995 Chevrolet Caprice,-31.36,152.39

# **`Sales Table`**

In [13]:
%%sql
select *
from sales
limit 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

# **`Date Table`**

In [12]:
%%sql
select *
from date
limit 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1
3,2015-01-04,20150104,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Sunday,Sun,1,0,1
4,2015-01-05,20150105,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Monday,Mon,2,1,2
5,2015-01-06,20150106,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Tuesday,Tue,3,1,3
6,2015-01-07,20150107,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Wednesday,Wed,4,1,4
7,2015-01-08,20150108,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,1,5
8,2015-01-09,20150109,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,6
9,2015-01-10,20150110,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,6

# **`Product Table`**

In [10]:
%%sql
select *
from product
limit 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
5,6,101006,Contoso 2G MP3 Player E200 Black,"Contoso, Ltd",Contoso,Black,ounces,8.80,11.00,21.57,1,Audio,101,MP4&MP3
6,7,101007,Contoso 2G MP3 Player E200 Blue,"Contoso, Ltd",Contoso,Blue,ounces,2.10,11.00,21.57,1,Audio,101,MP4&MP3
7,8,101008,Contoso 4G MP3 Player E400 Silver,"Contoso, Ltd",Contoso,Silver,ounces,5.60,30.58,59.99,1,Audio,101,MP4&MP3
8,9,101009,Contoso 4G MP3 Player E400 Black,"Contoso, Ltd",Contoso,Black,ounces,2.10,30.58,59.99,1,Audio,101,MP4&MP3
9,10,101010,Contoso 4G MP3 Player E400 Green,"Contoso, Ltd",Contoso,Green,ounces,11.00,30.58,59.99,1,Audio,101,MP4&MP3

# **`Store Table`**

In [11]:
%%sql
select *
from store
limit 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,storekey,storecode,geoareakey,countrycode,countryname,state,opendate,closedate,description,squaremeters,status
0,10,1,1,AU,Australia,Australian Capital Territory,2008-01-01,None,Contoso Store Australian Capital Territory,595.00,None
1,20,2,3,AU,Australia,Northern Territory,2008-01-12,2016-07-07,Contoso Store Northern Territory,665.00,Closed
2,30,3,5,AU,Australia,South Australia,2012-01-07,2015-08-08,Contoso Store South Australia,2000.00,Restructured
3,35,3,5,AU,Australia,South Australia,2015-12-08,None,Contoso Store South Australia,3000.00,None
4,40,4,6,AU,Australia,Tasmania,2010-01-01,None,Contoso Store Tasmania,2000.00,None
5,50,5,7,AU,Australia,Victoria,2015-12-09,None,Contoso Store Victoria,2000.00,None
6,60,6,8,AU,Australia,Western Australia,2010-01-01,None,Contoso Store Western Australia,2000.00,None
7,70,7,12,CA,Canada,New Brunswick,2007-05-07,2014-03-09,Contoso Store New Brunswick,1105.00,Restructured
8,72,7,12,CA,Canada,New Brunswick,2015-01-11,2018-02-02,Contoso Store New Brunswick,1500.00,Restructured
9,74,7,12,CA,Canada,New Brunswick,2018-06-02,None,Contoso Store New Brunswick,3500.00,None

# **`Net Revenue`**

In [16]:
%%sql
select quantity * netprice * exchangerate as net_revenue, *
from sales
limit 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,net_revenue,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,63.49,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,423.28,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,108.75,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1146.75,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,950.25,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1302.91,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,58.73,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,224.98,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,263.11,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,578.52,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

# **`Sales >= 2020`**

In [17]:
%%sql
select quantity * netprice * exchangerate as net_revenue, *
from sales
where orderdate::DATE >= '2020-01-01'
limit 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,net_revenue,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,99.47,1827000,0,2020-01-01,2020-01-02,593517,999999,1810,4,28.80,27.94,14.68,EUR,0.89
1,139.97,1827000,1,2020-01-01,2020-01-02,593517,999999,1809,6,28.80,26.21,14.68,EUR,0.89
2,669.39,1827000,2,2020-01-01,2020-01-02,593517,999999,698,2,376.00,376.00,172.90,EUR,0.89
3,4090.60,1827000,3,2020-01-01,2020-01-02,593517,999999,364,6,765.90,765.90,390.48,EUR,0.89
4,237.15,1827001,0,2020-01-01,2020-01-01,307502,80,1288,2,101.39,91.25,51.69,CAD,1.30
5,1507.16,1827002,0,2020-01-01,2020-01-01,1413265,430,2061,3,546.07,502.39,180.92,USD,1.00
6,189.35,1827002,1,2020-01-01,2020-01-01,1413265,430,1717,3,63.12,63.12,29.02,USD,1.00
7,539.90,1827002,2,2020-01-01,2020-01-01,1413265,430,435,1,539.90,539.90,275.26,USD,1.00
8,5590.00,1827003,0,2020-01-01,2020-01-01,1567083,570,451,5,1118.00,1118.00,514.12,USD,1.00
9,3580.00,1827004,0,2020-01-01,2020-01-01,1855428,550,535,10,358.00,358.00,164.64,USD,1.00

# **`Combine Sales, Customer and Product Tables`**

In [25]:
%%sql
SELECT
  s.orderdate,
  c.customerkey,
  c.givenname,
  c.countryfull,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname,
  s.quantity * s.netprice * s.exchangerate AS net_revenue
FROM sales s
LEFT JOIN
  customer c ON c.customerkey = s.customerkey
LEFT JOIN
  product p ON p.productkey = s.productkey
WHERE
  orderdate::DATE >= '2020-01-01'
LIMIT 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,net_revenue,orderdate,customerkey,givenname,countryfull,continent,productkey,productname,categoryname,subcategoryname
0,99.47,2020-01-01,593517,Heike,Germany,Europe,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games
1,139.97,2020-01-01,593517,Heike,Germany,Europe,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games
2,669.39,2020-01-01,593517,Heike,Germany,Europe,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax"
3,4090.60,2020-01-01,593517,Heike,Germany,Europe,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops
4,237.15,2020-01-01,307502,Michelle,Canada,North America,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories
5,1507.16,2020-01-01,1413265,Jason,United States,North America,2061,Contoso Microwave 1.5CuFt X0110 Silver,Home Appliances,Microwaves
6,189.35,2020-01-01,1413265,Jason,United States,North America,1717,MGS Flight Simulator X M250,Games and Toys,Download Games
7,539.90,2020-01-01,1413265,Jason,United States,North America,435,Adventure Works Desktop PC1.60 ED160 White,Computers,Desktops
8,5590.00,2020-01-01,1567083,James,United States,North America,451,WWI Desktop PC2.30 M2300 Silver,Computers,Desktops
9,3580.00,2020-01-01,1855428,Johnny,United States,North America,535,WWI LCD19W M100 White,Computers,Monitors

# **`High Revenue VS Low Revenue ($1000USD) from 2020 To Present`**

In [29]:
%%sql
SELECT
  s.orderdate,
  c.customerkey,
  c.givenname,
  c.countryfull,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname,
  s.quantity * s.netprice * s.exchangerate AS net_revenue,
  CASE WHEN s.quantity * s.netprice * s.exchangerate >= 1000 THEN 'HIGH' ELSE 'LOW' END as high_low_revenue
FROM sales s
LEFT JOIN
  customer c ON c.customerkey = s.customerkey
LEFT JOIN
  product p ON p.productkey = s.productkey
WHERE
  orderdate::DATE >= '2020-01-01'
LIMIT 10

Running query in 'postgresql+psycopg2://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,customerkey,givenname,countryfull,continent,productkey,productname,categoryname,subcategoryname,net_revenue,high_low_revenue
0,2020-01-01,593517,Heike,Germany,Europe,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games,99.47,LOW
1,2020-01-01,593517,Heike,Germany,Europe,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games,139.97,LOW
2,2020-01-01,593517,Heike,Germany,Europe,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax",669.39,LOW
3,2020-01-01,593517,Heike,Germany,Europe,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops,4090.60,HIGH
4,2020-01-01,307502,Michelle,Canada,North America,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories,237.15,LOW
5,2020-01-01,1413265,Jason,United States,North America,2061,Contoso Microwave 1.5CuFt X0110 Silver,Home Appliances,Microwaves,1507.16,HIGH
6,2020-01-01,1413265,Jason,United States,North America,1717,MGS Flight Simulator X M250,Games and Toys,Download Games,189.35,LOW
7,2020-01-01,1413265,Jason,United States,North America,435,Adventure Works Desktop PC1.60 ED160 White,Computers,Desktops,539.90,LOW
8,2020-01-01,1567083,James,United States,North America,451,WWI Desktop PC2.30 M2300 Silver,Computers,Desktops,5590.00,HIGH
9,2020-01-01,1855428,Johnny,United States,North America,535,WWI LCD19W M100 White,Computers,Monitors,3580.00,HIGH